name: CI

on:
  pull_request:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Execute tests
      run: ./gradlew check
    - name: Execute lint checks
      run: ./gradlew androidApp:lint
